name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: true
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Setup example config
        run: cp ./src/config.example.rs ./src/config.rs
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: true
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Setup example config
        run: cp ./src/config.example.rs ./src/config.rs
      - name: Build
        run: cargo build --release
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            target/xtensa-esp32-espidf/release/todoesp
            target/xtensa-esp32-espidf/release/booloader.bin
            target/xtensa-esp32-espidf/release/partition-table.bin
          